name: CI Build

on:
  push:
    branches: [ main ]
    tags: ['**']
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'    
  pull_request:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build --verbosity normal


# MAUI Android Build
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore #Catharsium.Apps.PoolScoreboard/Catharsium.Apps.PoolScoreboard.csproj

      - name: Build MAUI Android
        run: dotnet publish Catharsium.Apps.PoolScoreboard/Catharsium.Apps.PoolScoreboard/.csproj -c Release -f net6.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: PoolScoreboard-android-ci-build
          path: Catharsium.Apps.PoolScoreboard/bin/Release/net6.0-android/*Signed.a*


# MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore Catharsium.Apps.PoolScoreboard/Catharsium.Apps.PoolScoreboard.csproj

      - name: Build MAUI Windows
        run: dotnet publish Catharsium.Apps.PoolScoreboard/Catharsium.Apps.PoolScoreboard.csproj -c Release -f net6.0-windows10.0.19041.0 --no-restore

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: PoolScoreboard-windows-ci-build
          path: Catharsium.Apps.PoolScoreboard/bin/Release/net6.0-windows10.0.19041.0/win10-x64/AppPackages/Catharsium.Apps.PoolScoreboard*/Catharsium.Apps.PoolScoreboard*.msix


# MAUI iOS Build
  build-ios:
    runs-on: macos-12
    name: iOS Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build MAUI iOS
        run: dotnet build Catharsium.Apps.PoolScoreboard/Catharsium.Apps.PoolScoreboard.csproj -c Release -f net6.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: PoolScoreboard-ios-ci-build
          path: Catharsium.Apps.PoolScoreboard/bin/Release/net6.0-ios/iossimulator-x64/**/*.app


# MAUI MacCatalyst Build
  build-mac:
    runs-on: macos-12
    name: MacCatalyst Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build MAUI MacCatalyst
        run: dotnet publish Catharsium.Apps.PoolScoreboard/Catharsium.Apps.PoolScoreboard.csproj -c Release -f net6.0-maccatalyst --no-restore -p:BuildIpa=True

      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: PoolScoreboard-macos-ci-build
          path: Catharsium.Apps.PoolScoreboard/bin/Release/net6.0-maccatalyst/maccatalyst-x64/publish/*.pkg
